### PR TITLE
feat: landing page

### PR DESCRIPTION
**Pull request by Arshie13**
## Contributors

**List all contributors to this PR:**

**- Aaron Ciervo**
**- Faithnina Marie Magsael**
**- Jezerwel Griño**

## Changes Overview

Finishing the mock up of landing page

### 🚀 New Features

- guest landing page with mocked data

## 🐛 Known Issues 

List any known issues or limitations:

- Issue 1: Data used is static

### CODE REVIEW

**Comment by Jezerwel** [comment]
fix landing page design

**Comment by Jezerwel** [comment]
Revert commits on test files, test dependencies, and test setup. Put it in separate branch and create a pull request

**Review by fnmrie — APPROVED** [review]

**Review by Jezerwel — CHANGES_REQUESTED** [review]
Revert commits on test files, test dependencies, and test setup. Put it in separate branch and create a pull request. Also fix landing page issue
@Arshie13

**Review by Jezerwel — CHANGES_REQUESTED** [review]
Revert commits on test files, test dependencies, and test setup. Put it in separate branch and create a pull request.
@Arshie13

**Review by Jezerwel — APPROVED** [review]

**Pull request merged**
